name: par2cmdline release build

on:
  push:
    branches:
    - 'turbo'

jobs:
  build-check-linux:
    uses: ./.github/workflows/build-check-linux.yml

  build-check-windows:
    uses: ./.github/workflows/build-check-windows.yml

  build-check-macos:
    uses: ./.github/workflows/build-check-macos.yml

  build-linux:
    needs:
    - build-check-linux

    strategy:
      matrix:
        include:
        - arch: amd64
          configure_host: 
          xcc: 
        - arch: arm64
          configure_host: --host=aarch64-linux-gnu
          xcc: aarch64-linux-gnu-

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cyberjunk/gha-ubuntu-cross@v5
      with:
        arch: ${{ matrix.arch }}

    - name: automake
      run: ./automake.sh

    - name: configure
      run: ./configure ${{ matrix.configure_host }}
      env:
        CC: ${{ matrix.xcc }}gcc
        CXX: ${{ matrix.xcc }}g++
        LDFLAGS: -static -s

    - name: make
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-turbo-linux-${{ matrix.arch }}
        path: |
          par2
        retention-days: 5

  build-windows:
    needs:
    - build-check-windows

    strategy:
      matrix:
        include:
        - platform: x64
          name: x64
        - platform: ARM64
          name: arm64

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild -property:PlatformToolset=ClangCL -property:Configuration=Release -property:Platform=${{ matrix.platform }} par2cmdline.sln

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-turbo-win-${{ matrix.name }}
        path: |
          ${{ matrix.platform }}/Release/par2.exe
        retention-days: 5

  build-macos:
    needs:
    - build-check-macos

    strategy:
      matrix:
        include:
        - arch: amd64
          macos_image: macos-13
        - arch: arm64
          macos_image: macos-latest

    runs-on: ${{ matrix.macos_image }}

    steps:
    - uses: actions/checkout@v4

    - uses: ConorMacBride/install-package@v1
      with:
        # LLVM 18 introduced incompatible change with stock libc++ [https://github.com/Homebrew/homebrew-core/issues/178435#issuecomment-2270106398]
        brew: automake llvm@17
      # force past "The `brew link` step did not complete successfully"
      continue-on-error: true
    - run: |
        if [ -f "`brew --prefix llvm`/bin/clang" ]; then
          echo "CC=`brew --prefix llvm`/bin/clang" >> $GITHUB_ENV
          echo "CXX=`brew --prefix llvm`/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L`brew --prefix llvm`/lib -Wl,-rpath,`brew --prefix llvm`/lib" >> $GITHUB_ENV
          echo "CFLAGS=-I`brew --prefix llvm`/include" >> $GITHUB_ENV
          echo "CXXFLAGS=-I`brew --prefix llvm`/include" >> $GITHUB_ENV
        fi

    - name: automake
      run: ./automake.sh

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: strip
      run: strip par2

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-turbo-macos-${{ matrix.arch }}
        path: |
          par2
        retention-days: 5
